### ISSUE TITLE
i tried it but it dint work :(

### ISSUE THREAD

**Issue by Succubussix** [tsarpaul/GLORYHook#1]
for the test i copy the `ls` to my project

 
 

i clone and install your custom lief
then i tried to compile the hook similar the sh file you provide..

```python
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


char *gloryhook_strrchr(const char *s, int c){
	printf("STRRCHR HOOKED!\n");
	return strrchr(s, c);
}

char *gloryhook_getenv(const char *name) {
	printf("GETENV HOOKED!\n");
	return getenv(name);
}
```

and compile it
```
gcc -shared -zrelro -znow hook.c -o hook
```

now i execute this

```cmd
 sudo python3 glory.py ./ls ./hook -o ./yeet
```

it looks like this

```python
[+] Beginning merge!
Traceback (most recent call last):
  File "glory.py", line 459, in <module>
    merger = Merger([path1, path2], out_path)
  File "glory.py", line 406, in __init__
    self.binaries = [Binary64(p) for p in paths]
  File "glory.py", line 406, in <listcomp>
    self.binaries = [Binary64(p) for p in paths]
  File "glory.py", line 184, in __init__
    assert(len(read_segs) == 1)
AssertionError
```

if i tried to remove the ```assert(len(read_segs) == 1)```

```python
[+] Beginning merge!
[+] Injecting new PLT
Traceback (most recent call last):
  File "glory.py", line 465, in <module>
    merger.merge()
  File "glory.py", line 434, in merge
    self.new_binary.merge_plt(plt_code, binary)
  File "glory.py", line 257, in merge_plt
    self.inject(plt_code, plt_end_offset)
  File "glory.py", line 211, in inject
    self.update_injection_code(offset, size)
  File "glory.py", line 162, in update_injection_code
    new_asm, count = ks.asm(new_asm_str)
  File "/usr/local/lib/python3.8/dist-packages/keystone/keystone.py", line 213, in asm
    raise KsError(errno, stat_count.value)
keystone.keystone.KsError: Invalid operand (KS_ERR_ASM_INVALIDOPERAND)
```

I have ubuntu 20.04 installed in my vmware. with python 3.8..  got all the keystone, keystone engine, capstone, your custome lief, etc

i tried to print the line 162 new_asm_str var

```asm
mov rax, qword ptr [rip + 0x1eff9]; /// this is ok
push qword ptr [rip + 0x1ec6a]; /// this is ok
bnd jmp qword ptr [rip + 0x1ec6b];  /// this part is the error
```

I verify that by testing it like this 

```python
from keystone import *

ks = Ks(KS_ARCH_X86, KS_MODE_64)

lol = ks.asm("bnd jmp qword ptr [rip + 0x1ec6b]")

print(lol)

```

```python
Traceback (most recent call last):
  File "lol.py", line 31, in <module>
    lol = ks.asm("bnd jmp qword ptr [rip + 0x1ec6b]")
  File "/usr/local/lib/python3.8/dist-packages/keystone/keystone.py", line 213, in asm
    raise KsError(errno, stat_count.value)
keystone.keystone.KsError: Invalid operand (KS_ERR_ASM_INVALIDOPERAND)
```

it seems bnd is not supported ?

**Comment by gamedevgs** [comment]
in another attempt .i did not install successfully.
with error 
```CMake Error at api/python/CMakeLists.txt:123 (target_compile_features):
  target_compile_features The compiler feature "cxx_attribute_deprecated" is
  not known to CXX compiler

  "GNU"

  version 4.8.5```
